stages:
  - deploy

variables:
  APP_NAME: project-morgana

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: https://tu-discord.xyz/
  only:
    - master
  script:
    - git-push ssh://dokku@51.15.53.66:22/$APP_NAME